### ISSUE TITLE
3.3.0 crashes on map load

### ISSUE THREAD

**Issue by module0x90** [raiguard/Factorio-RecipeBook#104]
Hi,

I have just upgraded RB from 3.2.3 to 3.3.0 and I am always greeted with the following:

 268.575 Error AppManagerStates.cpp:1595: The mod Recipe Book (3.3.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_init()
__RecipeBook__/scripts/database/beacon.lua:9: attempt to call field 'from_dimensions' (a nil value)
stack traceback:
	__RecipeBook__/scripts/database/beacon.lua:9: in function 'beacon'
	__RecipeBook__/scripts/database.lua:55: in function 'build'
	__RecipeBook__/control.lua:177: in function <__RecipeBook__/control.lua:169>

Which other information do you require?

Regards

Tom

**Comment by raiguard** [comment]
You need to update the `Factorio Library` mod. I negelcted to update the dependency when I released 3.3.0. The dependency has been updated for 3.3.1.
