### ISSUE TITLE
Recipe page not found with Bob's mods enabled

### ISSUE THREAD

**Issue by jtgans** [raiguard/Factorio-RecipeBook#106]
#### Describe the Bug

RecipeBook reports "Object has no page in Recipe Book" when clicking on a yellow belt (internal ID: transport-belt), and when searching for "transport belt" in the main GUI, Recipe Book returns two entries for the yellow belt, one with a recipe (from Bob's Logistics) and another with no recipe at all. With "show internal names" checked, they both show as the same prototype name.

This occurs in both single player and multiplayer.

#### To Reproduce

1. Install Bob's Logistics
2. Create a sandbox map and take the starter pack, unlock all research
3. Place some yellow belts from the inventory
4. Alt-left click a placed belt
5. Observe the error message "Object has no page in Recipe Book"

Alternatively:

1. Install Bob's Logistics
2. Create a sandbox map and take the starter pack, unlock all research
3. Open Recipe Book
4. Search for "transport belt"
5. Observe two yellow transport belts in the list
6. Click on one, note the lack of a full recipe
7. Click on the other, note the full recipe

#### Save File and Username

My username is mondoshawan22. 
[_autosave3.zip](https://github.com/raiguard/Factorio-RecipeBook/files/8240139/_autosave3.zip)

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/8240140/factorio-current.log)

**Comment by raiguard** [comment]
This is all actually working as intended.

- The transport belt entity doesn't have a page yet, so the error is accurate. I will be adding pages for all common entities in 3.4.
- What you are seeing is the yellow belt item page, and the recipe page. The item page shows the recipes that it is an ingredient in, and product of, while the recipe page shows the transport belt recipe. The glyphs on each entry will tell you what kind of object it is, as well the title of the info window:

![image](https://user-images.githubusercontent.com/3515394/158077804-c98493ca-c89c-4695-b4d1-077e2b040e2d.png)

**Comment by jtgans** [comment]
Oho. That was subtle. Okay, coolio. Thanks for responding -- I think I get what's going on now. If I have cycles, I'll see if I can help out with adding that page, if you like. :D
