### ISSUE TITLE
New ignore recipe categories

### ISSUE THREAD

**Issue by LuziferSenpai** [raiguard/Factorio-RecipeBook#11]
Hey,

you should ignore these recipe-categories too:

"deep-storage-item",
"deep-storage-fluid",
"deep-storage-item-big",
"deep-storage-fluid-big",
"deep-storage-item-mk2/3",
"deep-storage-fluid-mk2/3"

from my mod DSU

**Comment by raiguard** [comment]
Thanks, I'll add these.
