### ISSUE TITLE
The mod Recipe Book (3.4.1) caused a non-recoverable error.

### ISSUE THREAD

**Issue by WilyeECoyote** [raiguard/Factorio-RecipeBook#117]
Hi

I am getting the following errors

On loading a savefile:
The mod Recipe Book (3.4.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_configuration_changed
__RecipeBook__/scripts/database/technology.lua:22: attempt to index local 'new_highest_ident' (a nil value)
stack traceback:
	__RecipeBook__/scripts/database/technology.lua:22: in function 'insert_science_packs'
	__RecipeBook__/scripts/database/technology.lua:81: in function 'technology'
	__RecipeBook__/scripts/database.lua:75: in function 'build'
	__RecipeBook__/control.lua:229: in function <__RecipeBook__/control.lua:222>

On new game:
The mod Recipe Book (3.4.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_init()
__RecipeBook__/scripts/database/technology.lua:22: attempt to index local 'new_highest_ident' (a nil value)
stack traceback:
	__RecipeBook__/scripts/database/technology.lua:22: in function 'insert_science_packs'
	__RecipeBook__/scripts/database/technology.lua:81: in function 'technology'
	__RecipeBook__/scripts/database.lua:75: in function 'build'
	__RecipeBook__/control.lua:180: in function <__RecipeBook__/control.lua:172>

**Comment by raiguard** [comment]
Could you please upload your save file?

**Comment by curiosity-a** [comment]
Also the case in 3.4.2: [seablock version buffer.zip](https://github.com/raiguard/Factorio-RecipeBook/files/8749130/seablock.version.buffer.zip)
