### ISSUE TITLE
Crash upon opening the recipe book

### ISSUE THREAD

**Issue by schaap** [raiguard/Factorio-RecipeBook#13]
In a multiplayer game I opened recipe book 1.3.3 (Rai's Lua Library 0.2.8 and Factorio 0.18.29) which caused all other players to immediately disconnect. As soon as the next player joined again the server crashed. Loading the savefile that I could make at that time as a single player game immediately crashes, apparently reproducably. Screenshot shows the error after opening the save as single player game. I have also attached the save to hopefully reproduce this issue.
![20200602201538_1](https://user-images.githubusercontent.com/956563/83555817-2dd13800-a50f-11ea-8d30-4a1cbe011f07.jpg)

[multiplayer.zip](https://github.com/raiguard/Factorio-RecipeBook/files/4718954/multiplayer.zip)

**Comment by schaap** [comment]
Funny thing is that we both reported. https://github.com/raiguard/Factorio-RecipeBook/issues/12 is one of the people that got kicked out of that same multiplayer because I opened recipebook.

**Comment by millerlarson** [comment]
I get this error now when I go to load my save.

**Comment by raiguard** [comment]
@millerlarson Could you please send me that save file?

**Comment by raiguard** [comment]
Please? If you can reproduce it in singleplayer that will GREATLY aid me in fixing the bug.

**Comment by millerlarson** [comment]
I'll have to keep trying.  For now my save is working, and if I recall, it had something to do with enabling/upgrading flib.

Beyond this, I'll have to go through my autosaves and hope I've got one that can product this error.

**Comment by millerlarson** [comment]
I'm so far still unable to product this error with any of my saves.  If I happen to have any luck, I'll be sure to send it your way.

**Comment by raiguard** [comment]
Dang it, thanks anyway.

I've been completely unable to reproduce this error so far, and I have absolutely no clue as to how it happens in the first place. But I'll keep trying!

**Comment by raiguard** [comment]
So I figured out how to reproduce it, and managed to find what I believe is the cause. I will release a patch later today. Please let me know if it works now!

**Comment by raiguard** [comment]
The patch is out now!

@schaap Please try it now. Also, you can remove Rai's Lua Library, that mod is deprecated and has been replaced by the Factorio Library.

**Comment by schaap** [comment]
I will ask our server admin to update and reenable the addon. Next session is Tuesday evening, we'll know more by then.

**Comment by schaap** [comment]
We've tested this last evening and it seems to be fixed. Good job and thanks for picking it up quickly!
