### ISSUE TITLE
Multiplayer crash

### ISSUE THREAD

**Issue by dacendoran** [raiguard/Factorio-RecipeBook#14]
The mod Recipe Book (1.3.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_string_translated (ID 149)
__RecipeBook__/scripts/lookup-tables.lua:10: attempt to index field 'translation_lookup_tables' (a nil value)
stack traceback:
	__RecipeBook__/scripts/lookup-tables.lua:10: in function 'add_lookup'
	__RecipeBook__/control.lua:235: in function <__RecipeBook__/control.lua:224>

**Comment by raiguard** [comment]
Duplicate of #13
