### ISSUE TITLE
Annoying crash, love your mod!

### ISSUE THREAD

**Issue by dacendoran** [raiguard/Factorio-RecipeBook#15]
![image](https://user-images.githubusercontent.com/29506995/84420888-ba06ed80-abe8-11ea-9b4c-5267fb9b5484.png)

**Comment by raiguard** [comment]
Duplicate of #13, and I actually already released a patch to fix this literally a few minutes before you posted. :D

**Comment by dacendoran** [comment]
pog, thank you.
