### ISSUE TITLE
localising failed

### ISSUE THREAD

**Issue by LuziferSenpai** [raiguard/Factorio-RecipeBook#16]
![image](https://user-images.githubusercontent.com/38015859/85142140-31232e00-b248-11ea-83bb-5f704c3acb2f.png)

Happens with train construction site

**Comment by raiguard** [comment]
I can't find this. How do you get to that screenshot?

**Comment by LuziferSenpai** [comment]
I had it in a MP play, inside the recipe tab with pure angels etc.

**Comment by raiguard** [comment]
I can't seem to find this recipe any more. All it shows me is level 1, I can't find any level 3's...

![image](https://user-images.githubusercontent.com/3515394/87380659-2eb6aa00-c550-11ea-98d9-14b24d04193e.png)

**Comment by LuziferSenpai** [comment]
You need to enable the setting ^^

**Comment by LuziferSenpai** [comment]
<img width="743" alt="factorio_1OkGcD5YKf" src="https://user-images.githubusercontent.com/38015859/88076879-e6fcd780-cb7a-11ea-9bb1-cd6c05e2a1e4.png">
Well, found another localisation bug ...

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/88463140-c5973680-ce6d-11ea-9234-b90644e788ea.png)

I still don't have that recipe. Is there another mod that is modifying them to add the electric variants?

**Comment by raiguard** [comment]
Well, the failed localisation isn't my fault, that's just how the mod is. As for the rich text image being broken, that's also not my fault, that's an issue with the rich text itself.

![image](https://user-images.githubusercontent.com/3515394/88463255-b2d13180-ce6e-11ea-9b6d-100823f27b2a.png)
