### ISSUE TITLE
Multiplayer dictionary translation?

### ISSUE THREAD

**Issue by lordfilo** [raiguard/Factorio-RecipeBook#17]
Hello, Im running quite a few mods on with this on a multiplayer server but the recipebook button is greyed out, when using the keybind to open it it gives me a  "Please wait, dictionary translation has not yet finished" but its been an hour. On singleplayer it works fine
Nevermind, if anyone else gets this just run recipe book first in single player and then move the map over to multiplayer.

**Comment by raiguard** [comment]
Could you please send me one of the save files that wasn't working for you? I would like to get this sorted.

If it ever happens again, you can run `/RecipeBook refresh-player-data` to (hopefully) fix it.
