### ISSUE TITLE
Recipe list selection crash

### ISSUE THREAD

**Issue by Zyin055** [raiguard/Factorio-RecipeBook#18]
Crashed happened while playing with the mod Krastorio 2 and clicking on "Coal" in the recipe book's selection list. I have not been able to reproduce the error after the first crash.

The mod Recipe Book (1.3.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::Custom event (ID 172)
__RecipeBook__/scripts/gui/info-base.lua:166: attempt to index local 'object_data' (a nil value)
stack traceback:
	__RecipeBook__/scripts/gui/info-base.lua:166: in function 'update_contents'
	__RecipeBook__/scripts/gui/info-base.lua:96: in function 'open'
	__RecipeBook__/scripts/gui/info-base.lua:191: in function 'open_or_update'
	__RecipeBook__/control.lua:182: in function <__RecipeBook__/control.lua:161>
	[C]: in function 'raise_event'
	__flib__/event.lua:126: in function 'raise'
	__RecipeBook__/scripts/gui/search.lua:88: in function 'handler'
	__flib__/gui.lua:352: in function 'dispatch_handlers'
	__flib__/gui.lua:138: in function <__flib__/gui.lua:138>
stack traceback:
	__flib__/event.lua:126: in function 'raise'
	__RecipeBook__/scripts/gui/search.lua:88: in function 'handler'
	__flib__/gui.lua:352: in function 'dispatch_handlers'
	__flib__/gui.lua:138: in function <__flib__/gui.lua:138>
stack traceback:
	[C]: in function 'raise_event'
	__flib__/event.lua:126: in function 'raise'
	__RecipeBook__/scripts/gui/search.lua:88: in function 'handler'
	__flib__/gui.lua:352: in function 'dispatch_handlers'
	__flib__/gui.lua:138: in function <__flib__/gui.lua:138>

**Comment by raiguard** [comment]
I cannot reproduce this either. Please update me if you manage to crash it again!
