### ISSUE TITLE
synchronization error

### ISSUE THREAD

**Issue by FadingFog** [raiguard/Factorio-RecipeBook#21]
This mod is (exactly) causing sync issues. Factorio latest 0.18.x version. Latest mod version.
https://pastebin.com/YYZ2E1Cz  <-- .log file

**Comment by raiguard** [comment]
I need more info. Could you send me a save file? Could you tell me what you did to cause the issue? Could you tell me what the issue _actually was?_ That log is confusing and I don't recognize the error it's giving.

**Comment by FadingFog** [comment]
It doesn't depend on save file (but if you need a list of mods or something else, then here it is)
[save.zip](https://github.com/raiguard/Factorio-RecipeBook/files/4977200/save.zip)  <-- save
This mod (RecipeBook) cause the issue. If turn it off, then everything is fine. You can see the problem in the video:
https://www.youtube.com/watch?v=8E1_romoaCg and https://www.youtube.com/watch?v=b3Ze8n4AJkU
first I create a game and my friend connects and vice versa

**Comment by raiguard** [comment]
My first instinct is that this is not my fault, but is rather an issue with your internet connection and/or the base game itself. I'm asking some other modders for their opinions as well before I make that the final verdict.

**Comment by raiguard** [comment]
Could you try it with the [Quick Item Search](https://mods.factorio.com/mod/QuickItemSearch) mod, and see if the same thing happens? Both of these mods have to build a full index of translations before they're usable, which involves passing around a lot of data very quickly. It could be that the connection between the client and server just isn't fast / powerful enough to handle it.

If the same thing happens with QIS, it'll add credence to that theory.

**Comment by FadingFog** [comment]
Yes, same error but without fps drops. And without these mods everything works fine and there is no desync. I have a download (not connection) speed of 4 mb/s andmy friend has 600 kb/s

**Comment by raiguard** [comment]
So, the problem is not in the mod design itself, the problem is the internet connection. While it is translating, it is simply having to pass too much data for the 600 kB/s internet connection to handle.

To handle this, I will add a setting to the Factorio Library mod to throttle the number of translations it does per tick. Once I release that, please update and try setting the translations per tick value to something really small (say, 5). Keep lowering it until your friend can keep up, or until you hit 1.

If it can't keep up even at just 1 per tick, then you're out of luck.

**Comment by raiguard** [comment]
Upon further consideration, I have decided against adding a setting for this. flib is a sort of pseudo-mod at the moment, and adding a mod setting to it would destroy that. So, unless you can acquire a better internet connection, I guess you won't be able to use this mod. I'm sorry!

**Comment by raiguard** [comment]
Someone else also had this problem, so I got off my high horse and added the setting. If you're still around, please give it a try and see if decreasing the number of translations per tick helps with your issue!
