### ISSUE TITLE
crash with Krastorio2

### ISSUE THREAD

**Issue by npuldon** [raiguard/Factorio-RecipeBook#22]
https://imgur.com/a/eGoVDZW

Was working okay for the first 20 hours of the game but then it suddenly crashed when opening the book to lookup the imersite recipe chain.

**Comment by raiguard** [comment]
Could you please provide your save file?

**Comment by raiguard** [comment]
I'm fairly certain that this is related to another issue that I just fixed, please try the new version once I release it.

**Comment by npuldon** [comment]
[_autosave1.zip](https://github.com/raiguard/Factorio-RecipeBook/files/4976153/_autosave1.zip)

**Comment by raiguard** [comment]
Ah, thanks, I'll take a look just in case.

**Comment by raiguard** [comment]
Well I can't reproduce it no matter what I try, so I'll assume that it's fixed.

**Comment by raiguard** [comment]
I've released the patch, please let me know if you encounter this crash again!
