### ISSUE TITLE
Crash after migration removed recipes

### ISSUE THREAD

**Issue by awdwyn** [raiguard/Factorio-RecipeBook#23]
I have a mod that adds dynamically generated recipes.  Partway through a game I turned off some of those recipes (in startup mod settings) and a few seconds after reloading the game recipe book crashed with the following error:

  67.640 Error MainLoop.cpp:1207: Exception at tick 7280242: The mod Recipe Book (2.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_string_translated (ID 149)
__RecipeBook__/scripts/gui/main/base.lua:476: bad argument #1 of 2 to 'lower' (string expected, got nil)
stack traceback:
	[C]: in function 'lower'
	__RecipeBook__/scripts/gui/main/base.lua:476: in function 'open_page'
	__RecipeBook__/scripts/gui/main/base.lua:343: in function 'create'
	__RecipeBook__/control.lua:244: in function <__RecipeBook__/control.lua:222>

**Comment by raiguard** [comment]
Could you please provide your save file, as well as any mods that you have customized?

**Comment by awdwyn** [comment]
Sorry, can't do that - my mods folder is 3.2gb and 90% has been customized include stuff I'm developing.

The mod in question (was) Quarry https://mods.factorio.com/mod/quarry before I tore out or changed most of it, but the recipe generation is the same - result looks like this:

	local recipe = {
		type = "recipe",
		name = "deepwell-matter",
		localised_name = { "recipe-name.quarry-recipe", "Matter" },
		category="quarry",
		ingredients = {},
		icon = "__Krastorio2__/graphics/icons/fluids/matter.png",
		icon_size = 64,
		energy_required = 100,
		subgroup = "raw-resource",
		order = "a",
		enabled = false,
		results = {{type = "fluid", name = "matter", amount = 1}}
	}
	data:extend({recipe})


Not sure if this helps, but I had searched for one of the recipes in recipe book before the removal so maybe that string was cached?

**Comment by raiguard** [comment]
It's all right, in this case I think I was able to figure out the issue. Please try the new version once I release it.

**Comment by awdwyn** [comment]
You bet, thanks for the quick response 👍

**Comment by raiguard** [comment]
The patch has been released.
