### ISSUE TITLE
Real Craft Time

### ISSUE THREAD

**Issue by AmericanPatriot6f0** [raiguard/Factorio-RecipeBook#24]
When opening the menu and looking at the craft time, one can only see the per machine time, and not the recipe time. The recipe time is much more useful for ratios, and it would be nice if you could add it. It would probably be the last time entry and use the stopwatch icon instead of the assembler. This could also be an option to replace the assembler specific times.

**Comment by raiguard** [comment]
Xterminator did a mod spotlight on this today and also requested this, so I'm going to add it. I didn't think that the base crafting time would be useful, but apparently I was wrong. It'll be in for the next version.

**Comment by AmericanPatriot6f0** [comment]
Thanks. That was a very quick response. I actually found this mod through the spotlight, and noticed that this would be useful in the hour or so I was using it(I replaced FNEI).

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/88996654-072f4380-d2ab-11ea-9dee-6f7af9b7ddef.png)

I'm not entirely happy with how it looks, but this is by far the easiest and fastest way. If I wanted to stick it into the ingredients box, I would have to do some pretty janky things to get it to work.

**Comment by AmericanPatriot6f0** [comment]
You should try darkening the background.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/89491569-cb91ef00-d76c-11ea-8b6d-b80d2fb4b6ae.png)
Managed to integrate it into the ingredients panels, I like this a lot better. Coming soon!

**Comment by raiguard** [comment]
This was released in v2.1.0 a few days ago.
