### ISSUE TITLE
Favorite Bar

### ISSUE THREAD

**Issue by LuziferSenpai** [raiguard/Factorio-RecipeBook#25]
Hey,

why not add a little sidebar left, right or moveable, which you can open and then see all your favorites, it should be scrollable when its too much.

**Comment by raiguard** [comment]
Hmm, I'll consider it, though it'll probably be disabled by default.

**Comment by raiguard** [comment]
I decided to simply have the mod open to the home page instead of preserving your session. The favorites bar just wasn't working out, and this is much easier. :)

You can disable this new behavior in the interface settings.
