### ISSUE TITLE
Non-recoverable error on save load after Factorio update

### ISSUE THREAD

**Issue by Inveli** [raiguard/Factorio-RecipeBook#26]
#### Describe the Bug

When I try to load my save after the recent Factorio update I receive the following error:

```
Error while running event RecipeBook::on_configuration_changed
__RecipeBook__/scripts/global-data.lua:295: attempt to index field 'available_to_forces' (a nil value)
stack traceback:
	__RecipeBook__/scripts/global-data.lua:295: in function 'set_recipe_available'
	__RecipeBook__/scripts/global-data.lua:330: in function 'check_force_recipes'
	__RecipeBook__/scripts/global-data.lua:351: in function 'check_forces'
	__RecipeBook__/control.lua:58: in function <__RecipeBook__/control.lua:51>
```

Disabling the mod lets me load the save just fine. If I save a copy of this save without the mod, then try and load this new save with the mod enabled again, I get a slightly different version of the error:

```
Error while running event RecipeBook::on_init()
__RecipeBook__/scripts/global-data.lua:295: attempt to index field 'available_to_forces' (a nil value)
stack traceback:
	__RecipeBook__/scripts/global-data.lua:295: in function 'set_recipe_available'
	__RecipeBook__/scripts/global-data.lua:330: in function 'check_force_recipes'
	__RecipeBook__/scripts/global-data.lua:351: in function 'check_forces'
	__RecipeBook__/scripts/global-data.lua:16: in function 'init'
	__RecipeBook__/control.lua:38: in function <__RecipeBook__/control.lua:33>
```

#### To Reproduce

On first save file ("Save 06"), sync mods then try to load the game, and you will get the error.

On second save file ("Save 07"), sync mods then enable Recipe Book as well, then load and you will get the second error.

#### Save file & Username

Username : Invelios

First Save: https://mega.nz/file/EtYmkApR#GF_NJe1u2_J0uRYQbnAcommLpiZJW08diVe3Vto-jJU

Second Save: https://mega.nz/file/UgI2jYII#FtcADcN1Qm3iIpkEtfCCIyiuoekghzCN3hlNSUbjUss

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/5059983/factorio-current.log)

**Comment by raiguard** [comment]
Thanks, fixed for the next version.
