### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by BJZ2** [raiguard/Factorio-RecipeBook#30]
It is not obvious (to me) that the recipe book has a home page, which is the only place you can find Favorites and History. I found myself wondering how to get the Favorites to show up after favoriting a recipe. Closing and reopening the book didn't reset it to the home page.

After searching, etc. multiple times, I felt like there was no home page. The search area is always there, but where are Favorites and History hiding? I'd like to see a Home button to the left of the Back button.

I think people will want easier access to Favorites and History. There is a button that opens Settings on the right. Perhaps a buttons to open Favorites and History on the left would be good.

Summary:
- Add Home button with a tip.
- Add Favorites button with a tip that mentions that it opens on the left.
- Add History button with a tip that mentions that it opens on the left.
- Change Settings button's tip to mention that it opens on the right.
- For consistency, make sure all buttons have tips. For example, the Close button does not have a tip.

Finally, thank you. I recently came across you Factorio mods and have been exploring them.

**Comment by raiguard** [comment]
Yes, the home screen is the low-hanging fruit of Recipe Book at the moment. I actually have a branch that has a WIP version of a favorites and history bar on the side, but I haven't finished it yet. It'll be coming in the future.

**Comment by BJZ2** [comment]
Groovy.  (The adjective, not the language.)

**Comment by raiguard** [comment]
I decided to simply change the default behavior so opening Recipe Book will open to the home page. This can be disabled in the settings.
