### ISSUE TITLE
Multiplayer connection Timeout

### ISSUE THREAD

**Issue by Tuetenk0pp** [raiguard/Factorio-RecipeBook#33]
#### Describe the Bug
Multiplayer connection timeout about 5 seconds after joyn. Any player that connects to the server will be kicked almost instantly.

#### To Reproduce
joyn a multiplayer game with 'recipe book 2.4.1' enabled.

after removing recipe book from the server the problem no longer occured. Also, previous versions of recipe book worked flawlessley.

#### Save file & Username
username: Tuetenk0pp
[Seablock_1.1.zip](https://github.com/raiguard/Factorio-RecipeBook/files/5762312/Seablock_1.1.zip)

#### Log file

unfortunately I don't have the complete logfile as it is overwritten, but I have the relevant extract:

`
894.576 ConnectionRequestReplyConfirm (type(ConnectionRequestReplyConfirm) ) from(IP ADDR:({84.190.208.130:64146}))
894.576 Refusing connection for address (IP ADDR:({84.190.208.130:64146})), username (Tuetenk0pp). UserVerificationMissing
896.268 ConnectionRequestReplyConfirm (type(ConnectionRequestReplyConfirm) ) from(IP ADDR:({84.190.208.130:62913}))
896.269 Refusing connection for address (IP ADDR:({84.190.208.130:62913})), username (Tuetenk0pp). ModStartupSettingMismatch
935.069 ConnectionRequestReplyConfirm (type(ConnectionRequestReplyConfirm) ) from(IP ADDR:({84.190.208.130:57219}))
935.069 Refusing connection for address (IP ADDR:({84.190.208.130:57219})), username (Tuetenk0pp). UserVerificationMissing
935.706 ConnectionRequestReplyConfirm (type(ConnectionRequestReplyConfirm) ) from(IP ADDR:({84.190.208.130:57221}))
935.707 Info ServerRouter.cpp:453: Replying to connectionRequest for address(IP ADDR:({84.190.208.130:57221})).
935.707 Info ServerSynchronizer.cpp:600: nextHeartbeatSequenceNumber(26881) adding peer(4)
935.726 Info ServerMultiplayerManager.cpp:780: updateTick(2383676) changing state from(InGame) to(InGameSavingMap)
935.795 Info ServerMultiplayerManager.cpp:930: updateTick(2383676) received stateChanged peerID(4) oldState(Ready) newState(ConnectedWaitingForMap)
936.194 Info ServerMultiplayerManager.cpp:997: UpdateTick(2383676) Serving map(/factorio/temp/mp-save-3.zip) for peer(4) size(3174458) crc(4245245841)
936.195 Info ServerMultiplayerManager.cpp:780: updateTick(2383676) changing state from(InGameSavingMap) to(InGame)
936.295 Info ServerMultiplayerManager.cpp:930: updateTick(2383676) received stateChanged peerID(4) oldState(ConnectedWaitingForMap) newState(ConnectedDownloadingMap)
938.458 Info ServerMultiplayerManager.cpp:930: updateTick(2383676) received stateChanged peerID(4) oldState(ConnectedDownloadingMap) newState(ConnectedLoadingMap)
939.610 Info ServerMultiplayerManager.cpp:930: updateTick(2383744) received stateChanged peerID(4) oldState(ConnectedLoadingMap) newState(TryingToCatchUp)
939.733 Info ServerMultiplayerManager.cpp:930: updateTick(2383752) received stateChanged peerID(4) oldState(TryingToCatchUp) newState(WaitingForCommandToStartSendingTickClosures)
939.734 Info GameActionHandler.cpp:4961: UpdateTick (2383752) processed PlayerJoinGame peerID(4) playerIndex(0) mode(connect) 
939.812 Info ServerMultiplayerManager.cpp:930: updateTick(2383756) received stateChanged peerID(4) oldState(WaitingForCommandToStartSendingTickClosures) newState(InGame)
983.712 Info ServerMultiplayerManager.cpp:1048: Disconnect notification for peer (4)
983.730 Info ServerMultiplayerManager.cpp:1048: Disconnect notification for peer (4)
983.730 Info ServerSynchronizer.cpp:619: nextHeartbeatSequenceNumber(28223) removing peer(4).
984.718 Info ServerMultiplayerManager.cpp:1195: Auto saving map as /factorio/saves/Seablock_1.1.zip
984.719 Info AppManager.cpp:420: Saving game as /factorio/saves/Seablock_1.1.zip
985.205 Info AppManagerStates.cpp:1930: Saving finished`

**Comment by raiguard** [comment]
v1.4.0 of the mod now includes descriptions, which have to be translated. This significantly increases the amount of translations the mod has to do when new players join.

flib has a map setting to decrease the speed of translations to mitigate this. Go into the map settings and turn down the translations per tick to 1, and see if that helps. It will take significantly longer for the mod to become available, but hopefully it will decrease the network load enough to let you join.

**Comment by raiguard** [comment]
Did you manage to get this solved?

**Comment by Tuetenk0pp** [comment]
Hi, sorry I forgot about it. Will post tonight! 🙏

**Comment by Tuetenk0pp** [comment]
I just tried to reproduce the issue but it's no longer occuring! Maybe some update solved it in the meantime? Did you change the default value of that setting? Thanks anyway, its a really nice mod!
