### ISSUE TITLE
Display recipe in another level

### ISSUE THREAD

**Issue by kubiix** [raiguard/Factorio-RecipeBook#34]
#### Is your feature request related to a problem? Please describe.

Until now, I was using FNEI, but I like the GUI of your mod, but i am missing one thing - to be able to list between multiple recipes with same product / ingredient.

#### Describe the solution you'd like

As described on picture 1 below, if search for material for example Molten Glass the second "column" of GUI will list this material Ingredient in / Product of recipes. If i click the recipe it would be nice to open it in third "column" to preserve search result in second "column". Optionally add navigating buttons, highlight currently displayed recipe and x/y hint

Same as when search for crafter to be able to walk through Compatible recipes - picture 2

#### Additional context
![GUI1](https://user-images.githubusercontent.com/10234344/103992795-ef7eb400-5194-11eb-8ac4-fb77e6619438.png)
![GUI2](https://user-images.githubusercontent.com/10234344/103992802-f1e10e00-5194-11eb-9d29-1f0ffe48dac5.png)

**Comment by trikiman** [comment]
Lol I'm here cus want to create a post like this.
But someone already post it.
P.s. this best mod for me. But if u add it will be more then best.

**Comment by raiguard** [comment]
Hmm, I'm not sure how something like this would work in regards to the session history and stuff. The codebase is designed to only have one page open at a time, so I would have to refactor things quite a bit to make this work.

I'll think about solutions.

**Comment by kubiix** [comment]
I have forked your repo during week an I currently I am extending the mod to support fluids temperature handling in mods like pY, where some fluids have different temperatures accross recipes. Should work also with other mods with small adjustments, but I have not tested it. I will have it ready for PR soon if you are interested to merge it back.
These change needed to refactor history little bit so maybe a have idea how to implement the 3rd page. The biggest chalenge for me will be extending the GUI. 
I have some miner things to tweak, which I will do in separate PR

**Comment by raiguard** [comment]
What a coincidence, I was actually going to look at temperatures soon. It shouldn't require any refactoring though, just update the string formatter to include it.

**Comment by raiguard** [comment]
I'm not sure that multi-page will happen anytime soon, if ever, but I did go and add custom-inputs for navigating back and forth through your session history with the back and forward buttons on your mouse. That should make navigation a bit easier.

**Comment by kubiix** [comment]
I have it ready, but it is same as with Fluid Temperatures i made before .. hacky as you say :) so no PR today

It look almost same as on pictures from first post
- shift click in material detail on recipe in ingredients in / product of opens 3rd level detail of recipe
- recipes displayed in 3rd level don't go to history but the recipe can be favorited or opened in Quick GUI
- the arrows browse through all recipes from ingredients in / product of

Not finished things are
- browse icons are same as for session and dont fit there nice
- UI don't recenter position when extra colum opens or closes
- the indcator (acual/total) is missing
- actual recipe is not highlighted in the list in material detail and if it is out of visible part of list, it is not focused
- 

And i have done it on my repo state in master, that is in state before your recent updates on fluids, so you can grab it from there, if you are interested and check how it works in real

**Comment by trikiman** [comment]
> I have it ready, but it is same as with Fluid Temperatures i made before .. hacky as you say :) so no PR today
> 
> It look almost same as on pictures from first post
> 
> * shift click in material detail on recipe in ingredients in / product of opens 3rd level detail of recipe
> * recipes displayed in 3rd level don't go to history but the recipe can be favorited or opened in Quick GUI
> * the arrows browse through all recipes from ingredients in / product of
> 
> Not finished things are
> 
> * browse icons are same as for session and dont fit there nice
> * UI don't recenter position when extra colum opens or closes
> * the indcator (acual/total) is missing
> * actual recipe is not highlighted in the list in material detail and if it is out of visible part of list, it is not focused
> * 3rd level is supported only for material detail, not for crafter
> 
> And i have done it on my repo state in master, that is in state before your recent updates on fluids, so you can grab it from there, if you are interested and check how it works in real
> 
> Actual screenshot from game
> ![obrazek](https://user-images.githubusercontent.com/10234344/107230141-f6f8dd80-6a1e-11eb-80f6-4835674cdb64.png)

nice

**Comment by raiguard** [comment]
I haven't come up with a solution for multi-page that I am happy with as of yet, but I did find a nice solution for highlighting the "last selected" item. This, along with supporting the back/forward buttons on the mouse, makes navigation much easier.

![2e0159e7-ff4b-4941-8477-2b2fbdc4aac2](https://user-images.githubusercontent.com/3515394/107693988-0f116c80-6c6c-11eb-9bc1-0e9a2d8081b3.gif)

**Comment by kubiix** [comment]
Highlighting of item by color is not ideal, it breaks the avalability distinguished by color
And I have also some plans with coloring item to yellow.
Can you try to do the highlighting by applying bold style to font and preserve color by item state?

**Comment by trikiman** [comment]
> I haven't come up with a solution for multi-page that I am happy with as of yet, but I did find a nice solution for highlighting the "last selected" item. This, along with supporting the back/forward buttons on the mouse, makes navigation much easier.

back/forward buttons need only for middle section

**Comment by raiguard** [comment]
> Highlighting of item by color is not ideal, it breaks the avalability distinguished by color
> And I have also some plans with coloring item to yellow.
> Can you try to do the highlighting by applying bold style to font and preserve color by item state?

I tried various other things, but none of them are turning out. For now, the font color remains. Sorry!

**Comment by raiguard** [comment]
> back/forward buttons need only for middle section

I'm not sure I understand what you mean by this.

**Comment by trikiman** [comment]
![image](https://user-images.githubusercontent.com/39918652/108397079-a7898d00-7228-11eb-9629-514e87d066a0.png)
only this middle section need history.

**Comment by raiguard** [comment]
Oh, yeah, we had already established that.

**Comment by raiguard** [comment]
Here's an idea that's been going around in my head - what if instead of being one GUI, RB was multiple GUIs? Sort of like how it used to be pre-2.0, but much better.

The idea is that search would be its own thing that would open off to one side, and you would search for the thing you want. Selecting it would open an info window with its own separate session history. It would default to having one, but you could use a modifier key (alt?) to open whatever you're opening in another window. You could arrange these windows however you want and open/close them at will.

What do you think?

**Comment by kubiix** [comment]
I am not sure if I can imagine it in action right now. Actually I have rewritten this comment three times while thinking about it. 
I see these main use cases, what I want to do in Recipe Book
1. Quickly search objects in the Book
2. Traverse through the Book jumping to different info pages in single window
3. For certain item or fluid list recipes where it figures as product or ingredient. (like FNEI offers, but I don't like its UI) This is extremely handy, when looking for recipe to consume byproduct from another  recipe and opposite 

Maybe interesting idea could be, transform Recipe Book to some kind of "internet browser" with multiple info pages as tabs with own session history. You will be able to search objects in the book and open in actual tab, new tab or popup window. The items in listboxes are actually hyperlinks, which can be opened in same tab, or new page as tab or new window. The first page in tab history or on empty tab will be the home page with favorites and global history of last items. The tab could be toggle to separate window and Back window to dock it as panel. There should be some place for tab headers to switch or close tabs, but I have no idea how to visualise them.

Hope I will have time during weekend to try a new variant of the Recipe lister from point 3 above, I think it should be separate window in current UI version, not 3rd column 

May I ask you to add some icons to your master branch? 
Small icons to TitleBar
- for statistics something like barchart
- reload icon something like in browser
Large icons into page like are Fluid and Technology buttons
- product of
- ingredient in
- two horizontal arrows like switch left and right

Thanks

**Comment by raiguard** [comment]
I honestly don't know what I would do for product of and ingredient in icons, why do you need them?

Anyway, something else I would like is adding a generic search button to the top of the GUI, like vanilla GUIs have, that will search the opened info page. This is another reason I want to see if separating search from info pages would work - having two search bars in one GUI doesn't really make sense to me. It's a complex design problem, so hopefully we can come up with something good.

In the meantime, I'll look forward to seeing what you come up with!

**Comment by kubiix** [comment]
The icons product of and ingredient in should be on info page for item and fluid to open new recipe lister window, where this object appears

**Comment by kubiix** [comment]
I have quite good progress but currently struggling with designing the window layout - I would like to try the lister window with layout as on the picture, but there are limitation that type of element can be nested to another an I am wasting too much time with it (looks like I am a guy messing with Factorio GUI)

![obrazek](https://user-images.githubusercontent.com/10234344/108683265-ae96f080-74f1-11eb-86d3-f51a5bcd4938.png)

Can you help me with it ? I believe this will be quite easy for you

Thanks

**Comment by raiguard** [comment]
So, I actually do not want multiple columns. The original version of this mod (pre-2.0) did that, and it was just a complete nightmare of GUI code. I switched to a single, wider column because it makes the GUI layouting 10,000x easier. I'm also not so sure about the tabs idea in general, but I'll reserve judgement on that until I see it.

**Comment by kubiix** [comment]
Ok, I will try another layout and post screenshot here

**Comment by raiguard** [comment]
I have officially decided to start from scratch on a new mod, which will be called Factoripedia. It will support opening multiple GUIs, so I will keep this issue in mind when developing it.

**Comment by kubiix** [comment]
I am curious what will happen to Recipe Book

**Comment by raiguard** [comment]
It will be updated to add Factoripedia as a dependency and remove all of its content, so the transition will happen mostly seamlessly. The reason for making a new mod as opposed to updating this one is simply because you can't change an internal mod name. So the name would be "Factoripedia" but the internal name would be "RecipeBook" forever.

As for _why_ I'm doing this, I want to add various info that is out of scope for a Recipe Book. With the scope limitation removed, I can add all sorts of useful information for reference that RB doesn't have.

**Comment by raiguard** [comment]
Well, I changed my mind again. Recipe Book will remain, and if I add a ton of stuff outside its scope, I'll rename it. In the meantime, I'm working on the GUI changes I mentioned. You can follow the progress on the v3.0.0 branch.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/117919416-321edd00-b2aa-11eb-9155-8d09828a5046.png)
Here is what list navigation will look like.

**Comment by raiguard** [comment]
Version 3.0 has (finally) been released, so I'm considering this case closed!
