### ISSUE TITLE
Omni crash

### ISSUE THREAD

**Issue by sproott** [raiguard/Factorio-RecipeBook#35]
#### Describe the Bug
 
When using Omni mods and selecting Omnifurnace in the recipe book, the map crashes.
 
#### To Reproduce
 
 
1. Open Recipe Book
2. Select the "Crafter" search mode
3. Search for Omnifurnace
4. Click on it
5. See error
 
#### Save file & Username
 
[Omni Recipe Book crash.zip](https://github.com/raiguard/Factorio-RecipeBook/files/5832578/Omni.Recipe.Book.crash.zip)
 
Username: sproott
 
#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/5832577/factorio-current.log)

**Comment by raiguard** [comment]
Fixed for the next release.
