### ISSUE TITLE
Non-recoverable error

### ISSUE THREAD

**Issue by Slayman** [raiguard/Factorio-RecipeBook#4]
Someone reported this with AngelBob
I have this with Py when drilling down a product chain, latest Factorio 0.18.
latest pysuite no PyAL

`12391.656 Error MainLoop.cpp:1202: Exception at tick 297461: The mod Recipe Book caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_gui_selection_state_changed (ID 58)
The mod Recipe Book caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::Custom event (ID 215)
RecipeBook/gui/info-base.lua:194: attempt to index local 'object_data' (a nil value)
stack traceback:
RecipeBook/gui/info-base.lua:194: in function 'update_contents'
RecipeBook/gui/info-base.lua:217: in function 'open_or_update'
RecipeBook/control.lua:433: in function 'handler'
RecipeBook/lualib/event.lua:86: in function <RecipeBook/lualib/event.lua:26>
[C]: in function 'raise_event'
RecipeBook/lualib/event.lua:263: in function 'raise'
RecipeBook/control.lua:65: in function 'handler'
RecipeBook/lualib/event.lua:86: in function <RecipeBook/lualib/event.lua:26>
stack traceback:
RecipeBook/lualib/event.lua:263: in function 'raise'
RecipeBook/control.lua:65: in function 'handler'
RecipeBook/lualib/event.lua:86: in function <RecipeBook/lualib/event.lua:26>
stack traceback:
[C]: in function 'raise_event'
RecipeBook/lualib/event.lua:263: in function 'raise'
RecipeBook/control.lua:65: in function 'handler'
RecipeBook/lualib/event.lua:86: in function <RecipeBook/lualib/event.lua:26>`

**Comment by raiguard** [comment]
This should be fixed in the most recent version. Can you confirm?

**Comment by raiguard** [comment]
Can you confirm if this has been fixed?

**Comment by Slayman** [comment]
As far as my installation goes neither does the game crash nor do i get another error.
so it's fixed for me.

**Comment by raiguard** [comment]
Sweet, thanks!
