### ISSUE TITLE
Hover over an item / recipe and open Recipe Book via a Hotkey to bring up the item directly or even pin it?

### ISSUE THREAD

**Issue by KaneHart** [raiguard/Factorio-RecipeBook#40]
#### Is your feature request related to a problem? Please describe.

So I tend to be a bit lazy using the Recipe Book Sadly unless I'm trying to learn / figure something out. 

#### Describe the solution you'd like

That being said I would use it a ton more if I could say I want to make robot frames ctrl + something while hovering over the item in the crafting inventory or my own inventory and boom have it popup or maybe even have the pin one popup showing the requirements so I can work on that task. 

#### Additional context

Thank you :)

**Comment by raiguard** [comment]
I would _absolutely love_ this feature, but unfortunately it is straight-up impossible to do. Mods cannot access vanilla GUIs whatsoever. I'm sorry!

**Comment by KaneHart** [comment]
Thanks and 100% understandable. I had a feeling this would be the case. Maybe once the expansion comes out we can re-ask for such a hook for it.

Thanks again really awesome mod :)

**Comment by raiguard** [comment]
Related interface request: https://forums.factorio.com/96125
