### ISSUE TITLE
Some minable ores are considered unresearched

### ISSUE THREAD

**Issue by GregorSamsanite** [raiguard/Factorio-RecipeBook#41]
#### Describe the Bug
Some modded ores appear as unresearched materials, and are not searchable as materials without checking show unresearched objects.  These ores are mined from autoplaced resources as the primary way of generating them, however there are also higher tech recipes that produce them from other resources.  They don't show as researched in Recipe Book until the recipe to produce them is unlocked, even though they are minable from the start of the game.

#### To Reproduce
Install the Nullius mod plus Recipe Book.  Start a new game.  Open Recipe Book.
Open Recipe Book.  Search by Material.
Type in Bauxite, Sandstone, or Limestone.  These basic minable resources will not show up.
Check Show Unresearched Objects option, and search again.  These resources are red.

#### Save file & Username
Username: anachrony
[RecipeBookOre.zip](https://github.com/raiguard/Factorio-RecipeBook/files/5979268/RecipeBookOre.zip)

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/5979275/factorio-current.log)

**Comment by raiguard** [comment]
I actually noticed this myself and already fixed it for the next version. Thanks for the report!
