### ISSUE TITLE
Newest (2.5.0) update has caused a non-recoverable error.

### ISSUE THREAD

**Issue by FormBurden** [raiguard/Factorio-RecipeBook#43]
Every time I try to log into my save, my save game fails to load.

#### To Reproduce

1. Just logging into my save after I updated to most recent 2.5.0.

Here is the error from within the game:
```

Error while running event RecipeBook::on_configuration_changed
__RecipeBook__/scripts/processors/item.lua:36: attempt to get length of field 'placeable_by' (a nil value)
stack traceback:
	__RecipeBook__/scripts/processors/item.lua:36: in function 'item_proc'
	__RecipeBook__/scripts/global-data.lua:38: in function 'build_recipe_book'
	__RecipeBook__/control.lua:62: in function <__RecipeBook__/control.lua:57>
```

[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/5992961/factorio-current.log)
[I Think I Get This 2.zip](https://github.com/raiguard/Factorio-RecipeBook/files/5992969/I.Think.I.Get.This.2.zip)

Hope this helps to get this solved.

**Comment by raiguard** [comment]
Dafuq. Space Exploration adds items to place characters!? That's weird.

Anyway, fixed for the next version.

**Comment by FormBurden** [comment]
Oh yeah, I think that's Bob's Character classes.

**Comment by FormBurden** [comment]
Awesome, just saw your update and everything works fine. Appreciate the fast work.
