### ISSUE TITLE
Crash if % literal is used in search

### ISSUE THREAD

**Issue by anupmurarka** [raiguard/Factorio-RecipeBook#46]
Upon searching for a recipe with the string "5%" in the name, the mod crashed

The mod Recipe Book (2.5.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_gui_text_changed (ID 2)
__RecipeBook__/scripts/gui/main/search.lua:132: malformed pattern (ends with '%')
stack traceback:
	[C]: in function 'find'
	__RecipeBook__/scripts/gui/main/search.lua:132: in function 'handle_action'
	__RecipeBook__/scripts/gui/main/base.lua:609: in function 'handle_action'
	__RecipeBook__/control.lua:101: in function <__RecipeBook__/control.lua:97>

not critical and seems reasonably self contained but happy to upload a save file and log file if the above isn't sufficient.

**Comment by raiguard** [comment]
Thanks, fixed for the next version.
