### ISSUE TITLE
Display fuel acceleration & speed percentages

### ISSUE THREAD

**Issue by modo-lv** [raiguard/Factorio-RecipeBook#48]
#### Describe the solution you'd like

Add acceleration / top speed info for fuels in the recipe book.

#### Additional context

Increased complexity mods like Nullius, Bob's, Angel's, Pyanodon's etc. have huge amounts of recipes, many of which aren't craftable by hand, and a common quality-of-life approach is hiding them from the player's menu and using the recipe book to look up the info. If any information is missing from the item description, there's no way to know it without looking it up in the tech tree (assuming it's even on there, as it is possible to have recipes unlocked without research) or manufacturing the item first.

**Comment by raiguard** [comment]
This feels like scope-creep for a recipe book. However, I an legitimately considering renaming the mod to something else, and adding as much of this kind of information to it as I possibly can for reasons like this. I will think about it.

**Comment by modo-lv** [comment]
Would it be easier and/or less feature-creepy to simply display the in-game tooltip on mouse-over somewhere? The info is in there, hovering the cursor over the item should work just fine. Since encountering this issue I've checked FNEI, and while its UI is pretty horrible overall, it does show the tooltips.

**Comment by raiguard** [comment]
Oh, yeah, sorry. I was thinking way bigger, like adding a list of entities to the material page.

Yeah, I can add that to the tooltips. I can't use the vanilla tooltips though, because the type of element I'm using doesn't have access to them.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/109755973-393bb780-7ba4-11eb-9393-630e0234e6c9.png)

I also added the fuel pollution multiplier.
