### ISSUE TITLE
Recipe Book with Pyanodon Life crashes

### ISSUE THREAD

**Issue by Madidas** [raiguard/Factorio-RecipeBook#50]
#### Describe the Bug

Looking at any of the modded ores makes Recipe Book go kaput.

#### To Reproduce

1. Open Recipe Book
2. Search Modded Ore (Tested with Lead & Quartz, Vanilla Ores work fine)
3. Click the ore in the search list
4. Kaput with error message

> The mod Recipe Book (2.5.2) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event RecipeBook::on_gui_click (ID 1)
> __RecipeBook__/scripts/formatter.lua:462: attempt to index local 'data' (a boolean value)
> stack traceback:
> 	__RecipeBook__/scripts/formatter.lua:462: in function 'tooltip'
> 	__RecipeBook__/scripts/formatter.lua:560: in function 'format_item'
> 	__RecipeBook__/scripts/formatter.lua:594: in function <__RecipeBook__/scripts/formatter.lua:575>
> 	(...tail calls...)
> 	__RecipeBook__/scripts/gui/main/info-list-box.lua:56: in function 'update'
> 	__RecipeBook__/scripts/gui/main/pages/item.lua:27: in function 'update'
> 	__RecipeBook__/scripts/gui/main/base.lua:581: in function 'open_page'
> 	__RecipeBook__/scripts/gui/main/base.lua:621: in function 'handle_action'
> 	__RecipeBook__/control.lua:101: in function <__RecipeBook__/control.lua:97>

#### Save file & Username

In-game username is Madidas.
And save file is here: [Py_Maze.zip](https://github.com/raiguard/Factorio-RecipeBook/files/6185228/Py_Maze.zip)

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/6185214/factorio-current.log)

EDIT: I do need to mention that I run Factorio in Linux, if that causes issues...

**Comment by leehuk** [comment]
I've hit the same bug, but with a simpler reproduction:

1. Open Recipe Book on a save where Sulfuric Acid is not researched
2. Ensure "Show Unresearched Objects" is disabled in settings
3. Select Uranium Ore

**Comment by raiguard** [comment]
Thanks, fixed for the next release.
