### ISSUE TITLE
Recipe Book failing to find new tech added by updating another mod

### ISSUE THREAD

**Issue by ceresward** [raiguard/Factorio-RecipeBook#51]
#### Describe the Bug

Hi raiguard, I got a [report](https://mods.factorio.com/mod/LogiNetChannels/discussion/605f82228f2218a3771b3d48) on the Logistic Network Channels mod page about a crash when trying to load a savegame using both Logistic Network Channels and Recipe Book after updating to the new Logistic Network Channels release.  After analyzing the error, I think there may be an issue in Recipe Book where it's not checking in all cases for new technologies being added to a map.

From the crash report, it appears that there is a call to [handle_research_updated](https://github.com/raiguard/Factorio-RecipeBook/blob/master/src/scripts/global-data.lua#L102-L113), where it is crashing because the [technology_data](https://github.com/raiguard/Factorio-RecipeBook/blob/master/src/scripts/global-data.lua#L106-L107) local has a nil value.  I believe this is happening because the latest version of my mod adds a new technology, and somehow this technology is not getting added to your globals table; so when the new tech gets researched, the handler ends up performing a nil index.

It looks to me like maybe the core problem is that [build_recipe_book](https://github.com/raiguard/Factorio-RecipeBook/blob/master/src/scripts/global-data.lua#L19) didn't get called when my mod was updated.  I can see in your [on_configuration_changed](https://github.com/raiguard/Factorio-RecipeBook/blob/master/src/control.lua#L57) that you call `global_data.build_recipe_book()`, but it looks like it only gets called if the configuration change was for your mod.  Maybe it should be rebuilding the recipe book for all configuration changes instead?  Since new technology, recipes, etc. can be added by any mod change, not just Recipe Book config changes.

#### To Reproduce

1. Create a map save using both Logistic Network Channels 1.0.12 and Recipe Book 2.5.2
2. Update Logistic Network Channels to version 1.1.0
3. Check in mod settings that "Logistic Network Channels > Channels require research" is disabled (may or may not matter, but it is the setting I used when I reproduced it)
3. Attempt to load the map save from the previous version

#### Save file & Username

Save file is attached.  In-game username is 'ceresward'

#### Log file

Log file is attached.

**Comment by ceresward** [comment]
[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/6216883/factorio-current.log)
[logiNetChannels 1.0.12_rb-bug.zip](https://github.com/raiguard/Factorio-RecipeBook/files/6216884/logiNetChannels.1.0.12_rb-bug.zip)

**Comment by raiguard** [comment]
Thanks for the report. `on_configuration_changed` is working just fine, it's just that Logistic Network Channels gets the event before Recipe Book does, and it updates stuff there. I added a `nil` check for the next release, which should fix it.
