### ISSUE TITLE
Filter select staying open when closing book

### ISSUE THREAD

**Issue by sproott** [raiguard/Factorio-RecipeBook#52]
#### Describe the Bug

The search by selection box stays open when closing the book with Esc.

#### To Reproduce

1. Open Recipe Book
2. Click on the search by selection box to open it
3. Press the Esc key to close Recipe Book
4. The selection is still visible

#### Save file & Username

Will add later if needed.

#### Log file

Same for this.

**Comment by raiguard** [comment]
Unfortunately this cannot be fixed, as this is a bug with the dropdown widget in the game's C++. I've reported it before, but it's such a minor issue that the devs won't fix it.
