### ISSUE TITLE
No way to hide disabled mod recipes

### ISSUE THREAD

**Issue by HerrRiz** [raiguard/Factorio-RecipeBook#53]
I'm seeing an issue in an Angelbob run where we get a bunch of recipes that aren't actually available.
For example, it shows a recipe for salt by cooking water in a chemical furnace.

In FNEI, unchecking "show disabled recipes" gets rid of that recipe and others like it.
RecipeBook doesn't seem to have that option yet, unless I missed it.

**Comment by raiguard** [comment]
Ok, added for the next version.
