### ISSUE TITLE
Feedback&Idee: Suche über Bezeichner name & prototype name

### ISSUE THREAD

**Issue by 1Jonny** [raiguard/Factorio-RecipeBook#55]
hallo, ich find es super das man einstellen kann ob man nach Bezeichner Name suchen will, oder ob man nach internen objekt namen suchen will.
![Suche](https://user-images.githubusercontent.com/86615109/123781515-a3573580-d8d4-11eb-8e59-1dd08f868664.PNG)
allerdings muss man immer umschalten, es währe cool wenn man auch einstellen kann das man nach beidem Gleichzeitig sucht.

also folgende Such Möglichkeiten:

entweder 
1.) Bezeichner Name
oder
2.) interner Prototype Objekt Name
oder
3.) Bezeichner Name & interner Prototype Objekt Name

ich würd mich freuen wenn du ein die 3. Option hinzufügst, dann muss ich nicht mehr umschalten.

Mit freundlichen Grüßen
Jonny

**Comment by raiguard** [comment]
Interesting idea, I'll add it for the next version.

**Comment by 1Jonny** [comment]
Danke 😁

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/127756693-7c594c26-4fda-4418-bdb1-0a81ad88e8db.png)


Implemented for v3.0. The `search type` setting will apply to both the actual search GUI and searching in info screens.
