### ISSUE TITLE
Recipe Book list of items/recipes empty until two characters entered in search.

### ISSUE THREAD

**Issue by 343N** [raiguard/Factorio-RecipeBook#57]
### Describe the Bug

Recipe Book does not show items/recipes until you enter at least two characters (last I used recipe book months ago, this was not the case, and there is no setting for this, and I could not find it under the changes in the Mod Portal changelog for the past year of mod updates, so I assume this is a bug, rather than a feature). 

I almost always use search, but it being empty initially _feels_ really wrong, especially when it used to be full.

### To Reproduce

1. Open Recipe Book, nothing will be shown.
2 (Optional). Search with one character, no results.

Be certain to reproduce the issue on the same save file that you upload.

### Save file & Username

[singleplayer.zip](https://github.com/raiguard/Factorio-RecipeBook/files/6924430/singleplayer.zip)

Upload the save file where the bug occured. If the file is too large for GitHub, use an alternative file service.

### In-game Username:
343N

### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/6924426/factorio-current.log)

**Comment by raiguard** [comment]
This is intentional in order to save performance. Not a bug.
