### ISSUE TITLE
grouping search results.

### ISSUE THREAD

**Issue by LargePrime** [raiguard/Factorio-RecipeBook#6]
If we assume a recipe that has several ways to make the item in question.

A search, currently, returns several of the same item, and you have to enter and back out of each to see each recipe.

I suggest group each matching result, perhaps with a count shown on the main screen UI

Clicking a non unique result would allow quick navagation to which specific recipe you are looking for.

Thank you for your mod

**Comment by raiguard** [comment]
I'll think of something. Search is getting a major refactor in the next feature update, so I might be able to do a few fancy things.

**Comment by raiguard** [comment]
So the next version won't have any improvements in this area, but the version after that will. I'm going to be completely rewriting the GUI in the future to combine the search and info GUIs into one, so you'll be able to quickly browse the search results to find what you're looking for.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/87380773-6f162800-c550-11ea-97fe-1663f38b0375.png)

So I did not implement grouping, but there are other interface changes / improvements that will mitigate this issue. First off, you can easily scroll through the results without being thrown out of the search GUI. Additionally, each entry has a tooltip where you can view its internal name, which sometimes has more info.

In the future, I plan on adding an abbreviated list of ingredients and products to recipe tooltips as well, for even more convenience.

**Comment by raiguard** [comment]
At this point, grouping is not going to happen, and probably isn't needed anymore with the new GUI.
