### ISSUE TITLE
Recipe Book Window unable to close

### ISSUE THREAD

**Issue by BM123499** [raiguard/Factorio-RecipeBook#60]
#### Describe the Bug

When I load a saved game that Recipe book were open, there will be a recipe book window that can't be closed. 

#### How To Reproduce

Host new game.
Open Recipe Book.
Save the game (without closing the Recipe Book Window).
Host the saved game again (it will show Recipe Book Window, but you won't be able to close. And when you open, you'll open another one).
Each time, it will open another Window that can't be closed.

#### Image

![image](https://user-images.githubusercontent.com/48841672/128723983-78fec006-65f4-4f0f-866c-cdf338c1e1df.png)

**Comment by raiguard** [comment]
Could you attach a save file? I am unable to reproduce this.

**Comment by BM123499** [comment]
Here: [c.zip](https://github.com/raiguard/Factorio-RecipeBook/files/6957316/c.zip)

**Comment by BM123499** [comment]
Detail: This problem just happen to me when I save the window opened while hosting. If I set as single player, this error doesn't happen.

**Comment by raiguard** [comment]
Ah, that's probably why I couldn't reproduce it - I was doing it on singleplayer. I'll let you know.

**Comment by raiguard** [comment]
Thanks for the report, this has been fixed for the next release.
