### ISSUE TITLE
Doesn't open after save and load of the game, even after disabling the mod, saving and re-enabling

### ISSUE THREAD

**Issue by NeveHanter** [raiguard/Factorio-RecipeBook#62]
#### Describe the Bug
Recipe Book doesn't open after saving the game and loading it back.
Disabling the mod, saving the game, re-enabling the mod and loading the game doesn't help.

#### To Reproduce
1. Load attached save game,
2. Try to open Recipe Book
3. Get message asking you to wait for it to load or enter the `/RecipeBook refresh-player-data` command,
4. Wait for couple of minutes (it didn't load after an hour),
5. Enter the `/RecipeBook refresh-player-data` console command, wait without any apparent success as after couple of minutes Recipe Book still doesn't open

#### Save file & Username
Save game: [PY04.zip](https://github.com/raiguard/Factorio-RecipeBook/files/6957553/PY04.zip)
Username: NeveHanter

#### Log file
Log file: [factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/6957554/factorio-current.log)

**Comment by raiguard** [comment]
Congratulations, you uncovered a tick-perfect edge case with my new dictionaries system! That means that you saved your game on the exact tick that you loaded it, then loaded that save. At least, that's the only way I can conceive of this happening.

Anyway, this fix will be in `flib`, not Recipe Book. I'll release the flib and RB updates at the same time.

**Comment by raiguard** [comment]
This also made me realize that `refresh-player-data` was completely broken, so I have removed the `/RecipeBook` command and replaced it with `/rb-refresh-all`. Hopefully that command will never need to be used!
