### ISSUE TITLE
Throws an exception with Industrial Display Plates or Display Plates mods when loading the save

### ISSUE THREAD

**Issue by NeveHanter** [raiguard/Factorio-RecipeBook#63]
#### Describe the Bug
Throws an exception during the load of the save game attached to issue #62 (linked below) when [Display Plates](https://mods.factorio.com/mod/DisplayPlates) or [Industrial Display Plates](https://mods.factorio.com/mod/IndustrialDisplayPlates) is used.
```
Error while running event RecipeBook::on_load()
__RecipeBook__/scripts/processors/technology.lua:36: attempt to index local 'recipe_data' (a nil value)
stack traceback:
	__RecipeBook__/scripts/processors/technology.lua:36: in function 'technology_proc'
	__RecipeBook__/scripts/recipe-book.lua:53: in function 'build'
	__RecipeBook__/control.lua:113: in function <__RecipeBook__/control.lua:106>
```

#### To Reproduce

1. Sync mods from the save game,
2. Download and enable `Display Plates` or `Industrial Display Plates` mod,
3. Load the save game,
4. Observe the mighty exception ⚔️

#### Save file & Username
Save game: [PY04](https://github.com/raiguard/Factorio-RecipeBook/files/6957553/PY04.zip)
Username: NeveHanter

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/6957586/factorio-current.log)

**Comment by raiguard** [comment]
Thanks for the report. This is actually the same thing as #59, so closing as a duplicate.
