### ISSUE TITLE
Update to v 3.0+ doesn't work with Industrial Revolution 2.

### ISSUE THREAD

**Issue by AssasinAsha** [raiguard/Factorio-RecipeBook#64]
#### Describe the Bug

After updating to v 3.0+, the mod breaks on new game start or world load.
Version 2.7.1 of Recipe Book works just fine.

#### To Reproduce

Grab Factorio version 1.1.37.
Install Industrial Revolution 2.2.3, Factorio Library 0.8.2 and Recipe Book 3.0.2
Start a new map or load an existing one.

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/6968996/factorio-current.log)

On an unrelated note, the Factorio Mod Portal link in the Downloads part of the readme page is borked.

**Comment by raiguard** [comment]
Thanks for the report, fixed for the next release.

I fixed the download link as well. Thanks!
