### ISSUE TITLE
Cant create sandbox world

### ISSUE THREAD

**Issue by Zetabite** [raiguard/Factorio-RecipeBook#67]
#### Describe the Bug

Error when trying to create a default world in sandbox

#### To Reproduce

1. Make new sandbox world with default parameters
2. Click play
3. Error

#### Save file & Username

Save File: N/A
Username: Zetabite

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/6985647/factorio-current.log)

**Comment by raiguard** [comment]
I can't reproduce this. Could you attach your `mod-list.json`?

**Comment by Zetabite** [comment]
If i can launch into a freeplay ill try

**Comment by Zetabite** [comment]
same result on freeplay, cant create a save.
```
The mod Recipe Book (3.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_init()
__RecipeBook__/scripts/processors/resource.lua:27: bad argument #1 of 2 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	__RecipeBook__/scripts/processors/resource.lua:27: in function 'resource_proc'
	__RecipeBook__/scripts/recipe-book.lua:52: in function 'build'
	__RecipeBook__/control.lua:107: in function <__RecipeBook__/control.lua:99>
```

**Comment by raiguard** [comment]
If that doesn't work either, disable RB and upload a fresh save containing all of your other mods.

**Comment by Zetabite** [comment]
kk

**Comment by Zetabite** [comment]
[ZetabiteModdedRecipeBookDebug.zip](https://github.com/raiguard/Factorio-RecipeBook/files/6985692/ZetabiteModdedRecipeBookDebug.zip)

**Comment by raiguard** [comment]
Thanks for the report. There were actually two crashes here, one because an item placed a resource (wut) and the other because a resource had no mining products (also wut). `nauvis-melange` is _weird_.

Fixed for the next release.
