### ISSUE TITLE
Non recoverable error

### ISSUE THREAD

**Issue by ChickenMissile** [raiguard/Factorio-RecipeBook#70]
#### Describe the Bug

Non recoverable error after opening radar in recipe book.

#### To Reproduce

1. Open recipe book
2. Search for radar and click on the object page
3. See error

Also noticed when you do control + b on a placed radar entity it displays the message "Object has no page in the recipe book"

#### Save file & Username

In game username: ChickenMissile
[Recipe book bug.zip](https://github.com/raiguard/Factorio-RecipeBook/files/6998692/Recipe.book.bug.zip)

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/6998709/factorio-current.log)

**Comment by raiguard** [comment]
Thanks for the report, fixed for the next release.
