### ISSUE TITLE
Multiplayer player stuck when desync

### ISSUE THREAD

**Issue by viniciuslrangel** [raiguard/Factorio-RecipeBook#72]
#### Describe the Bug

In a modded multiplayer, in the latest versions, the second player cannot move anymore after some seconds.

#### To Reproduce

1. Host a server
2. Let a friend join it
3. Wait some seconds

#### Save file & Username

SingletonFactorio

[Copia do Industrial Craft.zip](https://github.com/raiguard/Factorio-RecipeBook/files/7027704/Copia.do.Industrial.Craft.zip)

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/7027707/factorio-current.log)

**Comment by raiguard** [comment]
Can you and your colleague both do speed tests of your network connections? That could be contributing.

**Comment by viniciuslrangel** [comment]
I have more than 50 Mbps of upload and my friend about 10 Mbps of download. Our latency goes between 12 and 32ms. He does have lag sometime when he has anyone in his house. Not sure if you saw, but our modpack is pretty big and it's your mod doing some weird stuff.

But, good job, you did a great mod with a lot of essential features to me. Thanks

**Comment by raiguard** [comment]
Do you both use the same language, or are you using different languages in-game?

**Comment by viniciuslrangel** [comment]
I'm using it in English, my friend is set to Portuguese. If you can give me a brief how this works,

**Comment by raiguard** [comment]
Can you type this into the console, have your friend join and time out, then attach the log file?

`/c script.on_event(defines.events.on_string_translated, function() log("TRANSLATED "..game.tick) end)`

**Comment by oorzkws** [comment]
This happens to me on LAN. I believe it's related to the changes that resolved #56, or that's when it cropped up anyway. I changed translations-per-tick to 5 and it stopped at the same time but I'm not sure if the two correspond.

**Comment by raiguard** [comment]
So the `translations per tick` option is entirely legacy, and is used for the old translation module. I never thought I would have to add an option for the new module, but I guess I do. This will require some changes on the flib side as well.

**Comment by raiguard** [comment]
I've made the necessary change in flib. Once I release it, please update and try decreasing the `Dictionary levels per batch` setting.

**Comment by raiguard** [comment]
Were any of you able to find success with decreasing the `Dictionary levels per batch` setting?

**Comment by viniciuslrangel** [comment]
Sorry, I couldn't test it yet. I'll in a week or two

**Comment by viniciuslrangel** [comment]
Just tested today and even lowering it to 1 didn't solve the issue.

**Comment by raiguard** [comment]
Unfortunately I don't think I can solve this. There is just a lot of data to pass around with the janky translations system that Factorio uses. The only way to fix this would be to remove localised search from the mod and use actual localised strings for the GUI, which would tank performance and severely cripple the mod. I'm sorry.

**Comment by Bykow** [comment]
Just a heads up: I have the same issue on a multiplayer server

**Comment by raiguard** [comment]
Sourcehut ticket: https://todo.sr.ht/~raiguard/factorio-mods/7
