### ISSUE TITLE
Some settings aren't staying saved between game restarts

### ISSUE THREAD

**Issue by dgattey** [raiguard/Factorio-RecipeBook#76]
#### Describe the Bug

Thanks for a much better version of FNEI that's modern and customizable! Love it. Just a small settings bug I've noticed.

Between game restarts (full client restart, not just a save), some settings will revert to defaults. The most noticeable is the setting to turn off glyphs. But recipe categories will also reset, notable since I'm using Industrial Revolution and it has incineration/scrapping I need to have off. Haven't noticed anything else change but it's also not reproducible on demand. Just happens on the occasional restart. Maybe it's when other mods get updated/disabled/enabled? Not sure.

Thanks!

#### To Reproduce

1. Change "Show glyphs" to off
2. Save game
3. Restart Factorio (this one is shaky, maybe you also need to disable another mod before you do? Hard to reproduce).
4. Open game
5. Notice that the glyphs are appearing and the setting is on again

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

Username is dgattey on the (Dropbox) attached file (single player)
https://www.dropbox.com/s/qiysup7aa3g52uw/bug-recipe-book.zip?dl=0

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/7119421/factorio-current.log)

**Comment by raiguard** [comment]
Thanks for the report, fixed for the next release.
