### ISSUE TITLE
Suggestion: right click to jump to item instead of recipe

### ISSUE THREAD

**Issue by dgattey** [raiguard/Factorio-RecipeBook#77]
#### Is your feature request related to a problem? Please describe.

Sometimes, I'm trying to follow an item chain, like going from molten carbon steel to see how it's used in the end products. I'd like to be able to be on the page for molten carbon steel (item), look at all the ingredients, then click each one and look at all of _their_ ingredients. So a path might be molten steel -> steel plate -> reinforced steel plate -> shielded steel plate -> centrifuge, then I go back to look at molten steel -> steel plate -> small steel frame -> ... 

Right now, that chain requires searching molten steel, clicking on one of the "Ingredient in" entries, which brings me to the recipe, where I visually have to look down a bit, click on the corresponding entry under products, and then repeat that with the next item. Instead of item -> item -> item, it's item -> recipe -> item -> recipe -> item. For my usage, it's redundant when 95% of the time I'm just interested in the products, not the recipe itself.

#### Describe the solution you'd like

Either 1) a setting where you can say "jump to item instead of jump to recipe" upon clicking on an entry in "Products" in a Recipe, or 2) right click jumps you right to the item, and left click brings you to the recipe, like what happens today. A little shortcut for ease of use!

**Comment by raiguard** [comment]
The problem with this arises when a recipe has multiple products. Which one should it show in that case?

![image](https://user-images.githubusercontent.com/3515394/133943902-d2004e7b-c06a-4cba-8859-0964e8cf7191.png)

**Comment by dgattey** [comment]
Haven't used FNEI recently enough to know how it handles it, but there's a way they allow linking through items like this. I'd be perfectly fine with this only working for single item recipes though, I don't think that's unexpected.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/135734156-29875afb-9257-41ce-9058-9338b2027cbf.png)

I have implemented this for single-product recipes.
