### ISSUE TITLE
Suggestion: reordering sections in the Pages

### ISSUE THREAD

**Issue by dgattey** [raiguard/Factorio-RecipeBook#78]
#### Is your feature request related to a problem? Please describe.

LOVE that I can hide and show and collapse info via the Pages settings. Super useful. I'd also like to be able to reorder them, as I find ingredients/products to be more useful than the general section in a recipe, for example. I want to see the most useful info at a glance instead of having to parse the UI, but I can't do that easily and keep general uncollapsed as I prefer.

#### Describe the solution you'd like

Being able to hover above the section on the Pages settings, click down, and drag it up or down to reorder it in the UI.

**Comment by raiguard** [comment]
If I do add this, you won't be able to do it by dragging. That's simply not possible with the mod API. As cool as it would be. :(

**Comment by raiguard** [comment]
Unfortunately I just don't think this is going to happen. It would be an enormous amount of work that I cannot commit to. I'm sorry.
