### ISSUE TITLE
Add toggle in settings for "Show unresearched recipes"

### ISSUE THREAD

**Issue by npuldon** [raiguard/Factorio-RecipeBook#79]
#### Is your feature request related to a problem? Please describe.

Add a toggle in settings window for "Show unresearched recipes" so I can use the tree discovery mod with recipe book effectively.  Currently, I can hide tech in the tech tree I don't have prereqs using the discovery tree mod (mainly for more immersion in new mod packs) but I can't hide recipes in the recipe book mod I haven't researched yet, only entities. For instance, in Krastorio 2 all iron plate recipes are visible no matter what toggles are used in the recipe book settings windows since iron plate, the entity, is available from the beginning even those recipes aren't unlocked under later in the tech tree.

#### Describe the solution you'd like

Add toggle in settings for "Show unresearched recipes"

**Comment by raiguard** [comment]
Does unchecking `Show unresearched objects` not work for you?

![image](https://user-images.githubusercontent.com/3515394/135700221-5556d97d-4e5f-4a09-a53c-a06c43eb070e.png)

**Comment by npuldon** [comment]
No. It's not the objects but recipes for objects which is the subject of my
request.   Like a late tech gives a new recipe for an object we had at game
start.  A common occurrence in the big overhaul mods.  I'm looking for a
toggle for 'show unresearched recipes'

**Comment by raiguard** [comment]
I pulled up the exact scenario you're talking about and it works fine:

![image](https://user-images.githubusercontent.com/3515394/135733683-3a4d38ca-9fd5-443b-8bf7-e6acb9cd7715.png)

Could you send me a screenshot of what it's doing for you?

**Comment by raiguard** [comment]
Look in the settings GUI, third checkbox from the top. Uncheck that.

**Comment by npuldon** [comment]
Thank you.  I thought I had that unchecked before my initial post but perhaps not.  That works as I had hoped.

Have a good day.

**Comment by raiguard** [comment]
No problem!
