### ISSUE TITLE
Version 3.2.0 crashes on Startup

### ISSUE THREAD

**Issue by AeroCross** [raiguard/Factorio-RecipeBook#83]
Hi!

The latest version (from an hour ago) is crashing on startup.

```
The mod Recipe Book (3.2.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_configuration_changed
__RecipeBook__/scripts/gui/info/root.lua:262: attempt to index local 'gui_data' (a number value)
stack traceback:
	__RecipeBook__/scripts/gui/info/root.lua:262: in function 'destroy'
	__RecipeBook__/scripts/gui/info/root.lua:273: in function 'destroy_all'
	__RecipeBook__/scripts/player-data.lua:155: in function 'refresh'
	__RecipeBook__/control.lua:140: in function <__RecipeBook__/control.lua:129>
```

It would appear that this is related to the changes in relation to the default settings.

**Comment by raiguard** [comment]
Could you please send your save file?

**Comment by dsbert** [comment]
I updated and got the same error.
Running k2, space exploration, and a few other utility mods

**Comment by raiguard** [comment]
Could one of you please provide your save file?

**Comment by dsbert** [comment]
[k2.zip](https://github.com/raiguard/Factorio-RecipeBook/files/7494055/k2.zip)

**Comment by AeroCross** [comment]
[Industrial Revolution 2.zip](https://github.com/raiguard/Factorio-RecipeBook/files/7494517/Industrial.Revolution.2.zip)

I am running Industrial Revolution 2, plus other also minor utility mods.

**Comment by oorzkws** [comment]
Ran into the same, the above saves probably have less dependencies than mine. Disabling RB, saving, and re-enabling the mod will allow you to use it again in your save in the meantime.

**Comment by daliborfilus** [comment]
Having the same problem, using Space Exploration with some AAI requirements, no K2.

**Comment by raiguard** [comment]
Thank you all, fixed for the next release.
