### ISSUE TITLE
Text color for not yet unlocked tech

### ISSUE THREAD

**Issue by npuldon** [raiguard/Factorio-RecipeBook#9]
Hello, I was wondering if tech that hasn't been unlocked yet could be colored red like 'What is it really used for?' mod does as I think this is a helpful issue.

Right now, you can click on the tech to be taken to the tech tree and see the color shading there but it's another tech that can be avoided to get at the same info to make your mod more user friendly.

Thank you for considering my request.

**Comment by raiguard** [comment]
This is in for the next version!

**Comment by npuldon** [comment]
Sounds great.  Thanks!

**Comment by raiguard** [comment]
This is out in the most recent version!
