### ISSUE TITLE
Localized language issues

### ISSUE THREAD

**Issue by fangfang333** [raiguard/Factorio-RecipeBook#92]
In ZH-CN localization language, we have collected more than 500 Chinese entries of mod into one MOD.
After we update the localized terms, some interfaces of this mod will change only after creating a new archive.
People think we haven't updated the localized language, which is very embarrassing.

**Comment by raiguard** [comment]
This is known. The mod has to translate everything ahead of time, and doesn't rely on localized strings. This significantly improves performance and makes it possible to do localized search. To update the locale, type the `/rb-refresh-all` command.

There was unfortunately no way to do this automatically in single player.
