### ISSUE TITLE
Crash on loading save. After removing mods + more.

### ISSUE THREAD

**Issue by SGZ-Creations** [raiguard/Factorio-RecipeBook#99]
#### Describe the Bug

I removed some mods that where broken + adding 3 other mods that i wanted instead
then on loading save this issue pops up.
![image](https://user-images.githubusercontent.com/59801736/153895667-6f3e3bc6-9c19-4fb5-b8ec-0f2eda53f0f2.png)

#### To Reproduce
Note install a copple of mods not only the subjects.
1. Add modds u want to use and start a save. 1 of the mods can be -> (mod i used: Deep storage unit )
2.  Save & quite game.  then  (Remove mod i used: Deep storage unit ) 
3. Restart game and load save u just made. Error shown on image shold we viseble to u.

#### Save file & Username

[1.1.46 Bobs-Dark-Guns.zip](https://github.com/raiguard/Factorio-RecipeBook/files/8062074/1.1.46.Bobs-Dark-Guns.zip)

#### User Name
Sgamez

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/8062082/factorio-current.log)

#### Privatley alternated mods
[Customized.zip](https://github.com/raiguard/Factorio-RecipeBook/files/8062103/Customized.zip)

**Comment by SGZ-Creations** [comment]
Another note removing mod made me able to contiunue my save

**Comment by raiguard** [comment]
I was unable to reproduce this issue, and I'm unsure of how it's even possible that it happened. If you ever come across it again, please let me know.

**Comment by SGZ-Creations** [comment]
ok. i could add mod after no issue

**Comment by SGZ-Creations** [comment]
Tho i have no more info to give it's all of it

**Comment by SGZ-Creations** [comment]
tho i still have a save that breaks
